[package]
name = "id3-iced-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.14.0"
id3 = "1.13"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
